name: CI - Task Management Service

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.java'
      - 'pom.xml'
      - '.github/workflows/**'
  push:
    branches: [ main ]
    paths:
      - '**/*.java'
      - 'pom.xml'
      - '.github/workflows/**'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Print Java & Maven versions
        run: |
          java -version
          mvn -version

      # Run full verification BUT skip Spotless formatting check (temporary workaround)
      # Checkstyle, tests, and JaCoCo will still run.
      - name: Verify (skip Spotless)
        run: mvn -B -ntp clean verify jacoco:report -Dspotless.check.skip=true

      # Always upload Surefire reports to help debugging failing tests
      - name: Upload Surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: |
            **/target/surefire-reports/*.xml
            **/target/surefire-reports/*.txt
          if-no-files-found: ignore

      # Upload JaCoCo HTML site so you can download index.html and view coverage locally
      - name: Upload JaCoCo site
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-site
          path: '**/target/site/jacoco/'
          if-no-files-found: ignore