name: CI - Task Management Service

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.java'
      - 'pom.xml'
      - '.github/workflows/**'
  push:
    branches: [ main ]
    paths:
      - '**/*.java'
      - 'pom.xml'
      - '.github/workflows/**'

# Cancel previous runs for the same ref to keep the queue clean
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Print Java & Maven versions
        run: |
          java -version
          mvn -version

      # Style / lint (fail fast if style breaks)
      - name: Run Spotless & Checkstyle
        run: mvn -B -ntp spotless:check checkstyle:check

      # Unit tests + coverage (HTML at target/site/jacoco/index.html)
      - name: Run unit tests with coverage
        run: mvn -B -ntp clean test verify jacoco:report

      # Always upload test reports for debugging
      - name: Upload Surefire reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: |
            **/target/surefire-reports/*.xml
            **/target/surefire-reports/*.txt
          if-no-files-found: ignore

      # Upload JaCoCo site so you can download index.html and open locally
      - name: Upload JaCoCo site
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-site
          path: '**/target/site/jacoco/'
          if-no-files-found: ignore
